--- #YAML:1.0
name:                Text-Find-Scalar
version:             0.05
abstract:            Find scalar names in a text.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Renee Baecker <module@renee-baecker.de>
